disabled_rules: 
  - trailing_whitespace

excluded:
  - Pods

file_length:
  warning: 600

line_length:
  warning: 200 
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
