disabled_rules: 
  - trailing_whitespace

excluded:
  - Viba/Custom/Lottie
  - Pods

file_length:
  warning: 600

line_length:
  warning: 200 
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

function_body_length:
  warning: 60

type_body_length:
  warning: 400
