
disabled_rules:
  - type_body_length
  - trailing_whitespace
  - file_length
  - weak_delegate
  - discouraged_optional_collection
  - multiple_closures_with_trailing_closure
  - identifier_name
  - notification_center_detachment

excluded:
    - Viba/Custom/Lottie
    - Pods
    - R.generated.swift

opt_in_rules:
    - attributes
    - closure_spacing
    - conditional_returns_on_newline
    - discouraged_optional_collection
    - empty_count
    - empty_string
    - fatal_error_message
    - literal_expression_end_indentation
    - operator_usage_whitespace
    - overridden_super_call
    - prohibited_super_call
    - redundant_nil_coalescing
    - required_enum_case
    - switch_case_on_newline
    - unneeded_parentheses_in_closure_argument
    - identical_operands
    - toggle_bool
    - closure_end_indentation
    - collection_alignment
    - contains_over_first_not_nil
    # - discouraged_optional_boolean
    - empty_xctest_method
    - explicit_init
    - fallthrough
    # - first_where
    # - function_default_parameter_at_end
    # - identical_operands
    # - last_where
    - leading_whitespace
    - legacy_random
    # - multiline_arguments
    # - multiline_function_chains
    # - multiline_literal_brackets
    # - multiline_parameters
    # - overridden_super_call
    # - redundant_nil_coalescing
    # - redundant_type_annotation
    # - sorted_first_last
    - strong_iboutlet
    # - trailing_closure
    - trailing_comma
    - untyped_error_in_catch
    - unused_import
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - xct_specific_matcher
    - yoda_condition
    # - convenience_type
    # - force_unwrapping
    # - force_unwrapping
    # - modifier_order
    - identifier_name
    - unused_declaration

identifier_name:
  min_length: 
    warning: 2
    error: 2
  max_length:
    warning: 50
    error: 50

function_parameter_count:
    warning: 5
    error: 5

line_length:
    ignores_interpolated_strings: true
    warning: 300
    error:   1000
    ignores_urls: true
    ignores_function_declarations: true
    ignores_comments: true

mark:
    severity: error

empty_enum_arguments:
    severity: error

vertical_whitespace:
    severity: error

type_name:
    min_length:
      warning: 3
      error: 1
    max_length:
      warning: 50
      error: 60
    excluded: iPhone

function_body_length:
    warning: 50
    error: 60

cyclomatic_complexity:
    warning: 15
    error: 20
    ignores_case_statements: true

colon:
    flexible_right_spacing: false
    apply_to_dictionaries: true

nesting:
    type_level: 4
